Addef
madhavanmalolan/N pull request #2
Opened 2018-05-15 11:47 UTC by fabiobaser

2018-05-15 13:22 UTC, madhavanmalolan requested changes
These changes can be clubbed under an if-else to check platform.

2018-05-15 13:22 UTC, madhavanmalolan commented on n_mac
> +osascript -e 'display notification  "Exit code: '"$?"'" with Title "Command \"'"$1"'\" completed"'
Can we not put this in the same script with an if-else?

2018-05-15 13:22 UTC, madhavanmalolan commented on README.md
> +![Works on MacOS](https://img.shields.io/badge/Works%20On-MacOS-blue.svg)
Thanks for noticing this! :+1:

2018-05-16 02:22 UTC, madhavanmalolan commented
Closing this instead. Thanks for your contribution :100:

2018-05-16 02:22 UTC, closed without merging

2018-05-16 09:42 UTC, fabiobaser commented on n_mac
> +osascript -e 'display notification  "Exit code: '"$?"'" with Title "Command \"'"$1"'\" completed"'
Sure, i just didn't want to mess with your code at all. :)

2018-05-16 09:42 UTC, fabiobaser commented on README.md
> +![Works on MacOS](https://img.shields.io/badge/Works%20On-MacOS-blue.svg)
Not for that. Easy peasy 👍